// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package server

import (
	"context"

	"my-IMSystem/user-service/internal/logic"
	"my-IMSystem/user-service/internal/svc"
	user_user "my-IMSystem/user-service/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user_user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user_user.RegisterRequest) (*user_user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *user_user.GetUserRequest) (*user_user.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
