// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package server

import (
	"context"

	"my-IMSystem/user-service/internal/logic"
	"my-IMSystem/user-service/internal/svc"
	user_user "my-IMSystem/user-service/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user_user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetProfile(ctx context.Context, in *user_user.GetProfileReq) (*user_user.GetProfileResp, error) {
	l := logic.NewGetProfileLogic(ctx, s.svcCtx)
	return l.GetProfile(in)
}

func (s *UserServer) UpdateProfile(ctx context.Context, in *user_user.UpdateProfileReq) (*user_user.UpdateProfileResp, error) {
	l := logic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}

func (s *UserServer) BatchGetUsers(ctx context.Context, in *user_user.BatchGetUsersReq) (*user_user.BatchGetUsersResp, error) {
	l := logic.NewBatchGetUsersLogic(ctx, s.svcCtx)
	return l.BatchGetUsers(in)
}

func (s *UserServer) SearchUser(ctx context.Context, in *user_user.SearchUserReq) (*user_user.SearchUserResp, error) {
	l := logic.NewSearchUserLogic(ctx, s.svcCtx)
	return l.SearchUser(in)
}

func (s *UserServer) IsOnline(ctx context.Context, in *user_user.IsOnlineReq) (*user_user.IsOnlineResp, error) {
	l := logic.NewIsOnlineLogic(ctx, s.svcCtx)
	return l.IsOnline(in)
}
