// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户基本信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`                    // 是否被禁用
	Gender        int32                  `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`                        // 性别，0: 未知, 1: 男, 2: 女
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_common_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserInfo) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

// 获取用户个人资料
type GetProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReq) Reset() {
	*x = GetProfileReq{}
	mi := &file_common_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReq) ProtoMessage() {}

func (x *GetProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReq.ProtoReflect.Descriptor instead.
func (*GetProfileReq) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResp) Reset() {
	*x = GetProfileResp{}
	mi := &file_common_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResp) ProtoMessage() {}

func (x *GetProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResp.ProtoReflect.Descriptor instead.
func (*GetProfileResp) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// 更新用户资料
type UpdateProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"` // 个性签名/简介
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReq) Reset() {
	*x = UpdateProfileReq{}
	mi := &file_common_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReq) ProtoMessage() {}

func (x *UpdateProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateProfileReq) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfileReq) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type UpdateProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResp) Reset() {
	*x = UpdateProfileResp{}
	mi := &file_common_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResp) ProtoMessage() {}

func (x *UpdateProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateProfileResp) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 批量获取用户信息
// 这个请求可以用于获取多个用户的基本信息
type BatchGetUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []int64                `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersReq) Reset() {
	*x = BatchGetUsersReq{}
	mi := &file_common_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersReq) ProtoMessage() {}

func (x *BatchGetUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersReq.ProtoReflect.Descriptor instead.
func (*BatchGetUsersReq) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetUsersReq) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type BatchGetUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersResp) Reset() {
	*x = BatchGetUsersResp{}
	mi := &file_common_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersResp) ProtoMessage() {}

func (x *BatchGetUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersResp.ProtoReflect.Descriptor instead.
func (*BatchGetUsersResp) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetUsersResp) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// 搜索用户
// 这个请求可以用于根据关键词搜索用户
type SearchUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserReq) Reset() {
	*x = SearchUserReq{}
	mi := &file_common_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserReq) ProtoMessage() {}

func (x *SearchUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserReq.ProtoReflect.Descriptor instead.
func (*SearchUserReq) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *SearchUserReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*UserInfo            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserResp) Reset() {
	*x = SearchUserResp{}
	mi := &file_common_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserResp) ProtoMessage() {}

func (x *SearchUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserResp.ProtoReflect.Descriptor instead.
func (*SearchUserResp) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *SearchUserResp) GetResults() []*UserInfo {
	if x != nil {
		return x.Results
	}
	return nil
}

// 查询用户是否在线
type IsOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineReq) Reset() {
	*x = IsOnlineReq{}
	mi := &file_common_proto_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineReq) ProtoMessage() {}

func (x *IsOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineReq.ProtoReflect.Descriptor instead.
func (*IsOnlineReq) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *IsOnlineReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type IsOnlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineResp) Reset() {
	*x = IsOnlineResp{}
	mi := &file_common_proto_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineResp) ProtoMessage() {}

func (x *IsOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineResp.ProtoReflect.Descriptor instead.
func (*IsOnlineResp) Descriptor() ([]byte, []int) {
	return file_common_proto_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *IsOnlineResp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

var File_common_proto_user_user_proto protoreflect.FileDescriptor

const file_common_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1ccommon/proto/user/user.proto\x12\x04user\"\xb3\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\x12\x16\n" +
	"\x06gender\x18\a \x01(\x05R\x06gender\"!\n" +
	"\rGetProfileReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"4\n" +
	"\x0eGetProfileResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"p\n" +
	"\x10UpdateProfileReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\"-\n" +
	"\x11UpdateProfileResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x10BatchGetUsersReq\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\x03R\x04uids\"9\n" +
	"\x11BatchGetUsersResp\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.user.UserInfoR\x05users\")\n" +
	"\rSearchUserReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\":\n" +
	"\x0eSearchUserResp\x12(\n" +
	"\aresults\x18\x01 \x03(\v2\x0e.user.UserInfoR\aresults\"\x1f\n" +
	"\vIsOnlineReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"&\n" +
	"\fIsOnlineResp\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online2\xaf\x02\n" +
	"\x04User\x127\n" +
	"\n" +
	"GetProfile\x12\x13.user.GetProfileReq\x1a\x14.user.GetProfileResp\x12@\n" +
	"\rUpdateProfile\x12\x16.user.UpdateProfileReq\x1a\x17.user.UpdateProfileResp\x12@\n" +
	"\rBatchGetUsers\x12\x16.user.BatchGetUsersReq\x1a\x17.user.BatchGetUsersResp\x127\n" +
	"\n" +
	"SearchUser\x12\x13.user.SearchUserReq\x1a\x14.user.SearchUserResp\x121\n" +
	"\bIsOnline\x12\x11.user.IsOnlineReq\x1a\x12.user.IsOnlineRespB\rZ\v./user;userb\x06proto3"

var (
	file_common_proto_user_user_proto_rawDescOnce sync.Once
	file_common_proto_user_user_proto_rawDescData []byte
)

func file_common_proto_user_user_proto_rawDescGZIP() []byte {
	file_common_proto_user_user_proto_rawDescOnce.Do(func() {
		file_common_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_user_user_proto_rawDesc), len(file_common_proto_user_user_proto_rawDesc)))
	})
	return file_common_proto_user_user_proto_rawDescData
}

var file_common_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_proto_user_user_proto_goTypes = []any{
	(*UserInfo)(nil),          // 0: user.UserInfo
	(*GetProfileReq)(nil),     // 1: user.GetProfileReq
	(*GetProfileResp)(nil),    // 2: user.GetProfileResp
	(*UpdateProfileReq)(nil),  // 3: user.UpdateProfileReq
	(*UpdateProfileResp)(nil), // 4: user.UpdateProfileResp
	(*BatchGetUsersReq)(nil),  // 5: user.BatchGetUsersReq
	(*BatchGetUsersResp)(nil), // 6: user.BatchGetUsersResp
	(*SearchUserReq)(nil),     // 7: user.SearchUserReq
	(*SearchUserResp)(nil),    // 8: user.SearchUserResp
	(*IsOnlineReq)(nil),       // 9: user.IsOnlineReq
	(*IsOnlineResp)(nil),      // 10: user.IsOnlineResp
}
var file_common_proto_user_user_proto_depIdxs = []int32{
	0,  // 0: user.GetProfileResp.user:type_name -> user.UserInfo
	0,  // 1: user.BatchGetUsersResp.users:type_name -> user.UserInfo
	0,  // 2: user.SearchUserResp.results:type_name -> user.UserInfo
	1,  // 3: user.User.GetProfile:input_type -> user.GetProfileReq
	3,  // 4: user.User.UpdateProfile:input_type -> user.UpdateProfileReq
	5,  // 5: user.User.BatchGetUsers:input_type -> user.BatchGetUsersReq
	7,  // 6: user.User.SearchUser:input_type -> user.SearchUserReq
	9,  // 7: user.User.IsOnline:input_type -> user.IsOnlineReq
	2,  // 8: user.User.GetProfile:output_type -> user.GetProfileResp
	4,  // 9: user.User.UpdateProfile:output_type -> user.UpdateProfileResp
	6,  // 10: user.User.BatchGetUsers:output_type -> user.BatchGetUsersResp
	8,  // 11: user.User.SearchUser:output_type -> user.SearchUserResp
	10, // 12: user.User.IsOnline:output_type -> user.IsOnlineResp
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_user_user_proto_init() }
func file_common_proto_user_user_proto_init() {
	if File_common_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_user_user_proto_rawDesc), len(file_common_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_user_user_proto_goTypes,
		DependencyIndexes: file_common_proto_user_user_proto_depIdxs,
		MessageInfos:      file_common_proto_user_user_proto_msgTypes,
	}.Build()
	File_common_proto_user_user_proto = out.File
	file_common_proto_user_user_proto_goTypes = nil
	file_common_proto_user_user_proto_depIdxs = nil
}
