FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api-gateway ./api-gateway

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/api-gateway .
COPY --from=builder /app/api-gateway/etc ./etc
EXPOSE 8090
CMD ["./api-gateway", "-f", "etc/api.yaml"]
