// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ConnectReq struct {
	Token string `json:"token"` // 客户端连接时传入的 JWT token
}

type ConnectResp struct {
	Message string `json:"message"`
}
